  
GET https://api.minimumcrm.com/dev/MinimumCRMGatewayWS/functions/authenticate
Content-Type: application/json
###

POST https://api.minimumcrm.com/dev/MinimumCRMUserGatewayWS/functions/authenticate 
Content-Type: application/json

{
"email": "crm@minimumcrm.com" , "password": "Hermes35**"

}
###

GET https://api.minimumcrm.com/dev/MinimumCRMGatewayWS/functions/getEventLogs
Content-Type: application/json
###

POST https://api.minimumcrm.com/dev/MinimumCRMUserGatewayWS/functions/getEventLogs
Content-Type: application/json

{
"beginDate": "yyyy-MM-dd", "endDate": "yyyy-MM-dd"
}
